/*
* generated by Xtext
*/
package dk.sdu.mmmi.modular.ui.contentassist;

import dk.sdu.mmmi.modular.ui.contentassist.AbstractRobustCollaborationProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RobustCollaborationProposalProvider extends AbstractRobustCollaborationProposalProvider {

}
