/*
* generated by Xtext
*/
package dk.sdu.mmmi.modular.roco2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Roco2AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/sdu/mmmi/modular/roco2/parser/antlr/internal/InternalRoco2.tokens");
	}
}
