/*
 * generated by Xtext
 */
package dk.sdu.mmmi.modular.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RobustCollaborationUiModule extends dk.sdu.mmmi.modular.ui.AbstractRobustCollaborationUiModule {
	public RobustCollaborationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
