/*
* generated by Xtext
*/
package dk.sdu.mmmi.modular.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class RobustCollaborationOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
