/*
 * generated by Xtext
 */
package dk.sdu.mmmi.modular;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RobustCollaborationRuntimeModule extends dk.sdu.mmmi.modular.AbstractRobustCollaborationRuntimeModule {

}
