/*
 * generated by Xtext
 */
package dk.sdu.mmmi.modular.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RobustCollaborationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return dk.sdu.mmmi.modular.ui.internal.RobustCollaborationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return dk.sdu.mmmi.modular.ui.internal.RobustCollaborationActivator.getInstance().getInjector("dk.sdu.mmmi.modular.RobustCollaboration");
	}
	
}
