/*
* generated by Xtext
*/
package dk.sdu.mmmi.modular.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RobustCollaborationAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/sdu/mmmi/modular/parser/antlr/internal/InternalRobustCollaboration.tokens");
	}
}
