/*
 * generated by Xtext
 */
package dk.sdu.mmmi.modular.roco2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Roco2RuntimeModule extends dk.sdu.mmmi.modular.roco2.AbstractRoco2RuntimeModule {

}
